### ISSUE TITLE
Make resample_branch reproducible

### ISSUE THREAD

**Issue by sashabaranov** [e5-tu-do/lhcb_pid_resample#15]
Currently `resample_branch` uses `numpy.random.choice`, which throws different results each time.

Solution would be to use `numpy.random.seed(seed)`, which could be configurable via command-line argument or environment variable.

**Comment by KonstantinSchubert** [comment]
Good idea. I think a pull request would be appreciated.

I suggest we keep the old behavior for the case that no command-line argument is passed? @ibab ?
