### ISSUE TITLE
Usage without output_tree

### ISSUE THREAD

**Issue by sashabaranov** [e5-tu-do/lhcb_pid_resample#16]
Currently `resample_branch` writes output to another file.

It is possible to write to the same file though:

first you'll need to import

``` python
from rootpy.io import root_open
```

and then:

``` python
for task in config["tasks"]:
    logging.info('Running task {}'.format(task))
    array = root_numpy.root2array(options.source_file, treename=options.input_tree, branches=task["features"])
    df = pandas.DataFrame(array)
    for pid in task["pids"]:
        pid_column = pid["resampler"].sample(df.values.T)
        pid_column.dtype = None
        pid_column.dtype=[('{}'.format(pid['name']), 'f8')]
        print("Writing new {} to {}".format(pid['name'], options.source_file))
        with root_open(options.source_file, mode='a') as myfile:
            root_numpy.array2tree(pid_column, tree=myfile.Get(options.input_tree))
            myfile.write()

```

Is output_file used because it is really meant to, or is it hack-around now?

**Comment by KonstantinSchubert** [comment]
Hi Sasha,
I think output_file is used because it is really meant to.

The usage of output_file reflects a pattern where data files can be created, deleted or replaced, but never edited in place.
This is a pattern I adopted because it makes it easier to re-run parts of the analysis chain without having to start from zero.

I understand that this might seem odd to you if you are used to editing root files in-place.

**Comment by ibab** [comment]
Yeah, always creating a new file allows you to use the filesystem to infer whether a part of the workflow needs to be re-run, which seems to be the simplest way of making the analysis reproducible while minimizing the time you have to wait while developing it (And that's how tools like `make` work).

But I think it would be a good idea to automatically do the right thing when the input and output files are identical, in case users don't want to follow that workflow.
What do you think, @KonstantinSchubert?

**Comment by KonstantinSchubert** [comment]
Agreed.

Igor Babuschkin notifications@github.com schrieb am Do., 12. Mai 2016
10:33:

**Comment by sashabaranov** [comment]
I have two problems with current copying implementation:
1. It does destroy tree name. For example if initial one was like "BlahBlah/BlahBlah", output can be only "BlahBlah".
2. It does not copy nontrivial data types

The pattern of not modifying data in place can be achieved differently. You can do file copying in makefile and perform in-place modification of duplicate. Or you can store "clean" readonly copy of all analysis data, and do rsync to "dirty" copy, which can be modified.

In our analysis we use latter approach. It enables us to have single files with all weights/predictions/… which can be easily used by everyone.

Probably the `--inplace` flag can be implemented and everyone will be happy.

**Comment by KonstantinSchubert** [comment]
I think these are valid concerns.

I like the Idea of an - -inplace flag because it is specific. We can then
throw an informative error if an output file is specified together with the
- -inplace flag.

Sasha Baranov notifications@github.com schrieb am Do., 12. Mai 2016 12:22:
