### ISSUE TITLE
Remove RooBinning support from core, use binning_config.py instead.

### ISSUE THREAD

**Issue by KonstantinSchubert** [e5-tu-do/lhcb_pid_resample#18]
Maybe we should remove the whole RooBinning import/conversion stuff from the module and put it in its own file into a tools subdir.

Instead we could have a binning_config.py where the binning can be spelled out by the user or imported from RooBinning. (We should ship a template for the latter).

This also removes the dependency on PIDCalib

**Comment by ttekampe** [comment]
I would rather go the other way round and integrate this tool into PIDCalib.
