### ISSUE TITLE
Wrong command in ReadMe.txt, obsolete path in config.json

### ISSUE THREAD

**Issue by Kecksdose** [e5-tu-do/lhcb_pid_resample#2]
In my opinion the correct command to resample some tuples would be

```
python pidtool.py resample_branch <configfile> <source_file> <output_file>
```

Furthermore, the example path `/fhgfs/groups/e5/lhcb/PIDCalib/` seems to be obsolete.

**Comment by KonstantinSchubert** [comment]
Hi, thanks for your comment.

The  config.json - file is really just for illustration. Also I couldn't see the path `/fhgfs/groups/e5/lhcb/PIDCalib/` in there, where did you find it?

I will fix the other issue.
